graylog2:
  container_name: graylog2
  image: graylog2/allinone
  ports:
    - 9000:9000
    - 12201:12201
  volumes:
    - ./graylog2/data:/var/opt/greylog/data
    - ./graylog2/log:/var/log/graylog`

fluentd-gelf:
  container_name: fluentd-gelf
  build: .
  links:
    - graylog2
  ports:
    - 24224:24224

